# Generated by Django 3.2 on 2021-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='background',
            field=models.ImageField(default='background', upload_to=''),
            preserve_default=False,
        ),
    ]
