# Generated by Django 3.2 on 2021-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_gallery_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
